config/routes.rb
Rails.application.routes.draw do
  resources :messages

  resources :exhibits

  resources :museums

  get 'wxapi' => 'wechat#init'
  post 'wxapi' => 'messages#create'

end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :museum, inverse_of: :exhibits
  
  def to_s
    if start_at.nil? 
      return name + " " + location + "常设"
    else
      return name + " " + location + start_at.to_s(:num_short) + "/" +
          end_at.to_s(:num_short)
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  has_many :exhibits, inverse_of: :museum

  def to_s
    "#{name}\n" + exhibits.map(&:to_s).join("\n")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception

  rescue_from WechatError::NotValid, with: :access_denied

  def access_denied
    render text: "Access denied", status: :forbidden
  end
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  before_action :set_exhibit, only: [:show, :edit, :update, :destroy]

  # GET /exhibits
  # GET /exhibits.json
  def index
    @exhibits = Exhibit.all
  end

  # GET /exhibits/1
  # GET /exhibits/1.json
  def show
  end

  # GET /exhibits/new
  def new
    @exhibit = Exhibit.new
  end

  # GET /exhibits/1/edit
  def edit
  end

  # POST /exhibits
  # POST /exhibits.json
  def create
    @exhibit = Exhibit.new(exhibit_params)

    respond_to do |format|
      if @exhibit.save
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully created.' }
        format.json { render :show, status: :created, location: @exhibit }
      else
        format.html { render :new }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibits/1
  # PATCH/PUT /exhibits/1.json
  def update
    respond_to do |format|
      if @exhibit.update(exhibit_params)
        format.html { redirect_to @exhibit, notice: 'Exhibit was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibit }
      else
        format.html { render :edit }
        format.json { render json: @exhibit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibits/1
  # DELETE /exhibits/1.json
  def destroy
    @exhibit.destroy
    respond_to do |format|
      format.html { redirect_to exhibits_url, notice: 'Exhibit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibit
      @exhibit = Exhibit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibit_params
      params.require(:exhibit).permit(:name, :start_at, :end_at, :url, :museum_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /wxapi
  def create
    logger.debug "Msg received: #{request.raw_post}"

    coming_in = Hash.from_xml(request.raw_post)["xml"].map{ |k,v|
      {k.underscore => v}}.reduce(:merge);
    coming_in["create_time"] = Time.at coming_in["create_time"].to_i

    logger.debug "Msg parsed: #{coming_in.to_s}"

    @in_message = Message.new(filter_params coming_in)
    @in_message.save unless Message.where(msg_id: @in_message.msg_id).count > 0

    handle @in_message

    render "msg_text", format: :xml
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filter_params hsh
      hsh.slice("msg_id", "to_user_name", "from_user_name", 
                 "create_time", "msg_type", "content")
    end

    # Handle messages
    def handle message
      @reply = Message.new to_user_name: message.from_user_name,
          from_user_name: message.to_user_name,
          create_time: Time.now
      message.content = message.content.strip
      if message.content == "展览"
        museums = Museum.all
      else
        museums = [Museum.find_by(name: message.content)]
      end

      @reply.content = ""
      if museums
        museums.each do |museum|
          exhibits = museum.exhibits.where("start_at < ?",1.week.since).
                                     where("end_at > ?",Time.now)
          @reply.content += "#{museum.name}：\n" +
                            exhibits.map(&:to_s).join("\n")
        end
      else
        @reply.content = "听不懂0 0"
      end
    end
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
  before_action :set_museum, only: [:show, :edit, :update, :destroy]

  # GET /museums
  # GET /museums.json
  def index
    @museums = Museum.all
  end

  # GET /museums/1
  # GET /museums/1.json
  def show
  end

  # GET /museums/new
  def new
    @museum = Museum.new
  end

  # GET /museums/1/edit
  def edit
  end

  # POST /museums
  # POST /museums.json
  def create
    @museum = Museum.new(museum_params)

    respond_to do |format|
      if @museum.save
        format.html { redirect_to @museum, notice: 'Museum was successfully created.' }
        format.json { render :show, status: :created, location: @museum }
      else
        format.html { render :new }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /museums/1
  # PATCH/PUT /museums/1.json
  def update
    respond_to do |format|
      if @museum.update(museum_params)
        format.html { redirect_to @museum, notice: 'Museum was successfully updated.' }
        format.json { render :show, status: :ok, location: @museum }
      else
        format.html { render :edit }
        format.json { render json: @museum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /museums/1
  # DELETE /museums/1.json
  def destroy
    @museum.destroy
    respond_to do |format|
      format.html { redirect_to museums_url, notice: 'Museum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_museum
      @museum = Museum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def museum_params
      params.require(:museum).permit(:name, :home_url, :exhibit_url)
    end
end

app/controllers/wechat_controller.rb
class WechatController < ApplicationController
  before_filter :valid?

  def valid?
    signature = [RF_CONFIG["wechat"]["token"],
                 params[:timestamp], params[:nonce]].sort
    raise WechatError::NotValid unless
        params[:signature] == Digest::SHA1.hexdigest(signature.join)
  end

  def init
    render plain: params[:echostr]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/views/exhibits/_form.html.erb
<%= form_for(@exhibit) do |f| %>
  <% if @exhibit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibit.errors.count, "error") %> prohibited this exhibit from being saved:</h2>

      <ul>
      <% @exhibit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :museum %><br>
    <%= f.collection_select(:museum_id, Museum.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exhibits/edit.html.erb
<h1>Editing Exhibit</h1>

<%= render 'form' %>

<%= link_to 'Show', @exhibit %> |
<%= link_to 'Back', exhibits_path %>

app/views/exhibits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exhibits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start at</th>
      <th>End at</th>
      <th>Url</th>
      <th>Belongs to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibits.each do |exhibit| %>
      <tr>
        <td><%= exhibit.name %></td>
        <td><%= exhibit.start_at %></td>
        <td><%= exhibit.end_at %></td>
        <td><%= exhibit.url %></td>
        <td><%= exhibit.belongs_to %></td>
        <td><%= link_to 'Show', exhibit %></td>
        <td><%= link_to 'Edit', edit_exhibit_path(exhibit) %></td>
        <td><%= link_to 'Destroy', exhibit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibit', new_exhibit_path %>

app/views/exhibits/new.html.erb
<h1>New Exhibit</h1>

<%= render 'form' %>

<%= link_to 'Back', exhibits_path %>

app/views/exhibits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exhibit.name %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @exhibit.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @exhibit.end_at %>
</p>

<p>
  <strong>Url:</strong>
  <%= @exhibit.url %>
</p>

<p>
  <strong>Belongs to:</strong>
  <%= @exhibit.belongs_to %>
</p>

<%= link_to 'Edit', edit_exhibit_path(@exhibit) %> |
<%= link_to 'Back', exhibits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relicfans</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :msg_id %><br>
    <%= f.text_field :msg_id %>
  </div>
  <div class="field">
    <%= f.label :to_user_name %><br>
    <%= f.text_field :to_user_name %>
  </div>
  <div class="field">
    <%= f.label :from_user_name %><br>
    <%= f.text_field :from_user_name %>
  </div>
  <div class="field">
    <%= f.label :msg_type %><br>
    <%= f.text_field :msg_type %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>To user name</th>
      <th>From user name</th>
      <th>Msg type</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.msg_id %></td>
        <td><%= message.to_user_name %></td>
        <td><%= message.from_user_name %></td>
        <td><%= message.msg_type %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/msg_text.xml.erb
<xml>
<ToUserName><![CDATA[<%= @reply.to_user_name %>]]></ToUserName>
<FromUserName><![CDATA[<%= @reply.from_user_name %>]]></FromUserName> 
<CreateTime><%= @reply.create_time.to_i %></CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[<%= @reply.content %>]]></Content>
</xml>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Msg:</strong>
  <%= @message.msg_id %>
</p>

<p>
  <strong>To user name:</strong>
  <%= @message.to_user_name %>
</p>

<p>
  <strong>From user name:</strong>
  <%= @message.from_user_name %>
</p>

<p>
  <strong>Msg type:</strong>
  <%= @message.msg_type %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/museums/_form.html.erb
<%= form_for(@museum) do |f| %>
  <% if @museum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@museum.errors.count, "error") %> prohibited this museum from being saved:</h2>

      <ul>
      <% @museum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :home_url %><br>
    <%= f.text_field :home_url %>
  </div>
  <div class="field">
    <%= f.label :exhibit_url %><br>
    <%= f.text_field :exhibit_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/museums/edit.html.erb
<h1>Editing Museum</h1>

<%= render 'form' %>

<%= link_to 'Show', @museum %> |
<%= link_to 'Back', museums_path %>

app/views/museums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Museums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Home url</th>
      <th>Exhibit url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @museums.each do |museum| %>
      <tr>
        <td><%= museum.name %></td>
        <td><%= museum.home_url %></td>
        <td><%= museum.exhibit_url %></td>
        <td><%= link_to 'Show', museum %></td>
        <td><%= link_to 'Edit', edit_museum_path(museum) %></td>
        <td><%= link_to 'Destroy', museum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Museum', new_museum_path %>

app/views/museums/new.html.erb
<h1>New Museum</h1>

<%= render 'form' %>

<%= link_to 'Back', museums_path %>

app/views/museums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @museum.name %>
</p>

<p>
  <strong>Home url:</strong>
  <%= @museum.home_url %>
</p>

<p>
  <strong>Exhibit url:</strong>
  <%= @museum.exhibit_url %>
</p>

<%= link_to 'Edit', edit_museum_path(@museum) %> |
<%= link_to 'Back', museums_path %>